### ISSUE TITLE
Please create an AppData file for Torrent File Editor

### ISSUE THREAD

**Issue by hughsie** [drizt/torrent-file-editor#1]
Please consider writing and installing an AppData file with the application description and some screenshots, else Torrent File Editor looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't.

See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by drizt** [comment]
I will add. Thanks!

**Comment by drizt** [comment]
What is KDE Software Centers? Google doesn't know such word.

**Comment by drizt** [comment]
In really I can't find a way to see description and screenshots from AppData. I tried to use gnome-software and apper on my Fedora 20.

**Comment by hughsie** [comment]
Fedora 20 is too old to read the local AppData file, it only reads AppStream metadata from the distro. Fedora 21 (or GNOME 3.12+) will happy read the local file, or if you don't want to upgrade I'll happily take a screenshot for you if you send me the appdata file.

**Comment by drizt** [comment]
I will install F21. Which applications in F21 I can use to read AppData file? Also please add my question to [AppData Specification](http://people.freedesktop.org/~hughsient/appdata/) in Questions section.

**Comment by hughsie** [comment]
GNOME Software (installed by default)
