### ISSUE TITLE
No save dialogue when opening a new torrent

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#12]
No save dialogue when opening a new torrent even if the current torrent has unsaved changes.

**Comment by drizt** [comment]
Works for me. Provide steps to reproduce.

**Comment by zeromido** [comment]
FYI I currently have version 0.2.2 downloaded from sourceforge.
Here's exactly what happened:
I clicked the open button and opened a torrent file 
Changed the type of announce from string to integer
Clicked the open button again and opened a new torrent
No any dialogues, confirmations or warnings appeared
