### ISSUE TITLE
[REQ] Save dialogue new form

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#13]
The save dialogue would be better if it's like: Save - Don't Save - Cancel (like Microsoft Notepad). And The X button and ESC is for closing the dialogue without changing anything (like Microsoft Notepad).
For more information see Microsoft Notepad save dialogue.

**Comment by drizt** [comment]
Please provide screenshot.

**Comment by zeromido** [comment]
http://i.imgur.com/qk97PTc.png
