### ISSUE TITLE
A few English grammer suggestions

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#14]
In "Main" Tab Change "Url" to "URL" (that's the correct spelling)
In "Main" Tab Change Creation time to Date created (A more common term)
In "Files" Tab Change Make torrent to Calculate pieces hashes (Maybe it will confuse users between it and between save as).
In "Files" Tab Change Base folder to Parent folder (it's a more common term).

**Comment by drizt** [comment]
I agree with *URL*, *Date created* and *Calculate pieces hashes*.

**Comment by drizt** [comment]
I think to change *Base folder* term to *Torrent root folder* or *Torrent parent folder*. I haven't decided yet which prefer.
