### ISSUE TITLE
[REQ] Updating the remove file icon

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#16]
Most of the people are use to red x icons like this:
http://i.imgur.com/7g1B6Rc.png

**Comment by drizt** [comment]
I use standard system icons when possible. When system doesn't provide icons Gnome icons are used. Find [here](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html) list-remove.

**Comment by drizt** [comment]
Anyway button has tooltip which explains action. I don't think users will have problems with understanding function of the button.

**Comment by zeromido** [comment]
That's where I got the icon
https://www.iconfinder.com/icons/14125/cancel_cross_delete_remove_x_icon
It's using Creative Commons License and I quote from their website: 
You are free to:
Share — copy and redistribute the material in any medium or format
Adapt — remix, transform, and build upon the material
for any purpose, even commercially.

**Comment by drizt** [comment]
You're right. This license is good. I check with this list [Fedora good licenses](https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#Good_Licenses)

**Comment by drizt** [comment]
I changed the icon only for *Delete tree items*. It's correct. Delete and Remove has various senses, look at [here](http://english.stackexchange.com/questions/52508/difference-between-delete-and-remove/52509#52509). So for *Remove files* is used remove icon and for *Delete tree items* is used delete icon.

**Comment by zeromido** [comment]
Nice going. Keep it up!
