### ISSUE TITLE
Test new version

### ISSUE THREAD

**Issue by drizt** [drizt/torrent-file-editor#18]
Hello @zeromido.

I done some changes and improvments for Torrent File Editor. So I ask you to check these changes. New beta version you can download [here](https://fs06n2.sendspace.com/dl/ea222984383345b7831502344fdce6da/576fe9dc42dfac9f/bthtvr/torrent-file-editor-0.2.2-53-g5e5a454-x32.exe). 

Please check English translations and design. Was added Replace/Search dialog in Tree tab. Also fixed some your issues.

**Comment by zeromido** [comment]
Hello @drizt.
I'm terribly sorry for the late reply. I'll give you feedback ASAP. Nice work by the way :)

**Comment by zeromido** [comment]
Issues created. But I have a question. Why did you remove version number from window title?
Also, what about #8, #9, #10, #11, #15?
Deep regards :)

**Comment by drizt** [comment]
The most of programs do not use version number in theirs window title. So I've decided to follow this way too.

**Comment by zeromido** [comment]
I see.

**Comment by drizt** [comment]
More fixes and changes.
[torrent-file-editor-0.2.2-69-g8d716d2-x32.exe](http://rgho.st/6CXLMsHyB)

**Comment by zeromido** [comment]
I can say it's flawless. 
But I recommend you fixing #27 before the new release.
Good work :+1:

**Comment by drizt** [comment]
[torrent-file-editor-0.2.2-70-g3de00ae-x32.exe](http://rgho.st/6Nf2ks6HJ)

**Comment by zeromido** [comment]
Sorry for late reply but it took me a while to analyze the app (every time I start it I remember many ideas!)
Analysis:
If you clicked _Add folder_ the app will remember the root (parent) of the folder you selected not the folder itself. Although, if you clicked _Open_ and selected a file, then clicked _Add folder_ you can see the folder you selected! I don't know how?!
Also, by "Remembering the last folder you dragged-and-dropped a file from it" I meant that if you clicked _Open_ after you drag-and-drop a file, you see the folder you dragged-and-dropped from.
Also, the app now doesn't remember last folder after it's closed, though the reg key is written in the registry.
Note: If you can change the behavior of the app to save the last folder path in a config file with the app exe (like Nirsoft apps) it would be much better, and you can also add more options to the app.
What do you think of changing the _Access denied_ dialogue to this:
Access denied. Run as administrator? Yes | No
Adding Digital Signatures to the exe?
I also noticed that if you deleted a file from the files list the app doesn't detect the changes.

**Comment by drizt** [comment]
> What do you think of changing the Access denied dialogue to this:
> Access denied. Run as administrator? Yes | No
> Adding Digital Signatures to the exe?

I think it can be done with WinAPI but I use Qt framework. Write WinAPI inserts very hard work. I sure system folders are not popular places for .torrent or .dat files. So probably I refuse this feature. Or you need to find very good reasons why it should be done.

**Comment by drizt** [comment]
> I also noticed that if you deleted a file from the files list the app doesn't detect the changes.

It's OK. Need always do *Calculate Pieces Hashes*. Doing this automatically after each change not the good idea.

**Comment by zeromido** [comment]
> you need to find very good reasons why it should be done.

Well, my reason is "Be ready for every possibility", for example at Chrome Web Store, if an extension got updated when you are in it's page, Chrome Web Store will send you a message to tell you that the extension has been updated and you need to reload the page; see how they are ready for this low probability. Also, it's not necessary to be a system folder, maybe someone changed a folder permission to be accessed only by an administrator.
And what about adding Digital Signatures to the exe?

**Comment by smaragdus** [comment]
I know this is not the proper thread but I would like to ask- is there a change log? I could not find what is new in version 0.3.1 (changes from 0.3.0 to 0.3.1).

Regards and Happy New Year!

**Comment by drizt** [comment]
No changelog. You can obtain `git log`. In 0.3.1 fixed working with .lnk shortcuts on Windows and updated translations. That's it.

**Comment by smaragdus** [comment]
**@drizt**
Thank you for your answer.

**Comment by zeromido** [comment]
Why didn't you close the issue @drizt

**Comment by drizt** [comment]
You're right.
