### ISSUE TITLE
Warning - Can't make torrent for file without full path. Need to set base folder

### ISSUE THREAD

**Issue by Paderman** [drizt/torrent-file-editor#2]
Hello,

I want to edit an existing file from the internet. I want to remove any items like files and save to a new torrent file.

Message:
"Warning - Can't make torrent for file without full path. Need to set base folder"

Thanks in advance.

**Comment by drizt** [comment]
You need to have downloaded files on your disk and set path to them (base folder). When you remove or add files **always** `info.pieces` is changed. So need to calculate this value again for this need to have files.
