### ISSUE TITLE
Remember columns sizes in "Files" tab

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#21]
In "Files" tab remember columns sizes in (may require a config file preferably put it in the same folder the app is in)

**Comment by drizt** [comment]
Application is only single file without any settings. It is a philosophy of this application.

**Comment by zeromido** [comment]
So, how does it remember the last folder after it's closed.

**Comment by drizt** [comment]
Good question. It does Qt internally or WinAPI. I can't find this folder in registry. And I don't have ideas where to find. Maybe you have?

**Comment by zeromido** [comment]
I'll inspect it.

**Comment by zeromido** [comment]
Bingo! The app creates a reg key in:
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ComDlg32\LastVisitedPidlMRU
with the app name and last folder (in binary format)
After I deleted the key, I clicked open and the last folder was changed to Desktop.

**Comment by drizt** [comment]
Thanks )
