### ISSUE TITLE
Remove the extra empty column in "Files" tab

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#22]
There's an extra empty column in "Files" tab, please consider removing it.

**Comment by drizt** [comment]
Yeah, it's special column to aling '# pieces' column. Think about this column like a spacer.

**Comment by zeromido** [comment]
Can the column be resized without a spacer. 
I mean, you can resize a column even if it's alone (no other columns next to it) right?

**Comment by drizt** [comment]
Column can't be resized. It means total columns size will equals or more than table width.

**Comment by zeromido** [comment]
OK. If that empty column is necessary keep it :)
