### ISSUE TITLE
"Add Files" and "Add folder" in "Files" tab buttons suggestion

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#23]
In "Files" tab replace "Add Files" and "Add folder" with something similar to this http://i.imgur.com/a0GVmEj.png

**Comment by drizt** [comment]
Need to do two clicks instead of one. I do not see why it better than current design.

**Comment by zeromido** [comment]
I just don't like icons without names, I hate being forced to pause with the cursor on every button to read the tool tip. I want all buttons to be like the "New", "Open", "Save", etc.
And by the way, the design and icons in your screenshot is a lot better than what you sent me. Is that an another template? If it is. What do you think about adding options to switch between templates to satisfy all tastes?

**Comment by drizt** [comment]
Atm I don't want to add any options becouse it's simple portable one-file application.

**Comment by zeromido** [comment]
Oh, come on man. It's not a difficult option. I really like that template (I'm fond of dark colors!) And the icons express about what it does. I love it.
Also, what do you think about what I said:
"I just don't like icons without names, I hate being forced to pause with the cursor on every button to read the tool tip. I want all buttons to be like the "New", "Open", "Save", etc."

**Comment by drizt** [comment]
The most of applications use toolbars with icons and without texts. [Firefox](http://pix.toile-libre.org/upload/original/1467086995.png), [Notepad](http://pix.toile-libre.org/upload/original/1467086448.png) or [uTorrent](http://pix.toile-libre.org/upload/original/1467086616.png) for example. So current icons without texts are OK. Furthemore I do not program personal for you. So I tried to make something that want the most of users. I don't know opinion of the most but I believe that the most want to have only single .exe file and don't have any trash in registry. Atm I don't see any reasons to change my mind.

**Comment by zeromido** [comment]
OK. And what about that template in your screenshot?
