### ISSUE TITLE
In "Files" tab capitalize the first letter of every "Filter by" rule

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#24]
In "Files" tab capitalize the first letter of every "Filter by" rule. It's a minor English mistake.

**Comment by drizt** [comment]
I like the current form. Just think about this as full phrase (without combo box) *Filter by extension*

**Comment by zeromido** [comment]
Another idea, what do you think if you made it like the type list in "Tree tab"?

**Comment by drizt** [comment]
What do you mean?

**Comment by zeromido** [comment]
Show it on hover.

**Comment by drizt** [comment]
Not my fit.
