### ISSUE TITLE
When navigating to "Files" tab focus the first file

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#26]
When navigating to "Files" tab it would be better if the first file is focused. Just to spare the users from a single click :p

**Comment by drizt** [comment]
It would not be better. Imagine user temporary click on other tab to immediately returns back. So he lost the past scroll position it is not good. But due this issue I found another small bug. When opened a new file files list must be scrolled up.

**Comment by zeromido** [comment]
Here's an example for what I meant:
Open a file.
Navigate to "Files" tab if you clicked End or arrows nothing will happen; you need to either click on a file  or use the mouse scroll to use End or arrows.

**Comment by drizt** [comment]
Ah. Now I understand. Will fix.
