### ISSUE TITLE
Rename files in "Files" tab

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#30]
Add option to rename files in "Files" tab with a double-click on the file (also with the right-click menu in #9)

**Comment by drizt** [comment]
Do you mean rename only files in .torrent file? Or actually file name on the disk? In the first case hash of torrent will be changed and so it will be a new .torrent file. In the second case it has no sense renamed file can't be located on the disk and so can't be seeded.

**Comment by zeromido** [comment]
I meant renaming files only in the .torrent file. About the hash, so what? The app is called Torrent File Editor, so it meant to change .torrent files.

**Comment by drizt** [comment]
I can't imagine when such feature can be useful. Provide real word example.

**Comment by zeromido** [comment]
I created a torrent. Then I found out that a file's name was wrong, and I wanted to change it, without creating the whole torrent again; it would be a lot of pain with large torrent (calculating pieces hashes and all)

**Comment by drizt** [comment]
You can use Tree tab for this purposes. It's very rare case as I mentioned before.

**Comment by zeromido** [comment]
OK.

**Comment by tuxayo** [comment]
Thanks a lot for the workaround with the tree tab, I'll try that and report when I can.
