### ISSUE TITLE
Add progress bar when viewing "Raw" tab

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#31]
Add progress bar when viewing "Raw" tab (It takes a while to load especially with large torrents. So, add it to inform users that the app is working)
Also, when navigating between "Raw" and other tabs the app goes not responding (especially when it's still loading), so, try to rewrite the code make it easy to cancel and resume loading raw data.

**Comment by drizt** [comment]
Need to look the code. I do not sure that it can be fixed.

**Comment by drizt** [comment]
[This](https://github.com/drizt/torrent-file-editor/blob/master/mainwindow.cpp#L974) line eats 0.4 second on my PC. Decoded .torrent file very big for regular text editor. So it takes many time to load it. I haven't other widget for this purposes. So atm it can't be fixed.
