### ISSUE TITLE
Connect to trackers and verify if torrent successfully connects with them

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#32]
This maybe outside the app's purpose but I was using torrenteditor.com recently and it had that feature; so I thought you might like it.

**Comment by drizt** [comment]
What is mean *successfully connects*? Is it mean just ping host or need to do something else?

**Comment by zeromido** [comment]
http://i.imgur.com/iaLrpJg.png
As you can see, torrenteditor.com does what a torrent client does connect to trackers and check status. "This maybe outside the app's purpose but I was using torrenteditor.com recently and it had that feature; so I thought you might like it."

**Comment by drizt** [comment]
It requires to add extra library, probably [rasterbar libtorrent](http://www.libtorrent.org/). It will make compilation process very complicated. I use only Qt features.

**Comment by zeromido** [comment]
I thought so, that's why I said "This maybe outside the app's purpose but I was using torrenteditor.com recently and it had that feature; so I thought you might like it."
