### ISSUE TITLE
Remove copy link location and select all from about dialogue

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#33]
Remove copy link location and select all from about dialogue.

**Comment by drizt** [comment]
Which sense of these changes?

**Comment by zeromido** [comment]
Sorry about the typos. I meant when you right-click anywhere on the about dialogue, you see three actions, Copy, Copy Link Location and Select All. Select All is kinda unnecessary and Copy Link Location should only be shown when you right-click on a link.
P.S. Change "Copy Link Location" to "Copy link address" and "Select All" to "Select all".
I hope I made myself clear.

**Comment by drizt** [comment]
It's standart context menu from Qt. I didn't write any code for this. Also Firefux uses the such context menu entries. So it's ok.
