### ISSUE TITLE
Capitalizing hash value

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#39]
I don't think it's gonna be a big trouble, right?

**Comment by drizt** [comment]
Right. But what for it should be capitalized?

**Comment by zeromido** [comment]
Well, it just looks fancy like that.
I mean 
C76A4C45695180C31D922327139014C742FA2044 
looks better than 
c76a4c45695180c31d922327139014c742fa2044

**Comment by drizt** [comment]
I prefer lower-case.

**Comment by zeromido** [comment]
Whatever you say but don't forget that uTorrent uses upper-case characters.
