### ISSUE TITLE
E-mail

### ISSUE THREAD

**Issue by pafri** [drizt/torrent-file-editor#4]
Hi,

I´ve translated the localization file, but the attempt to use the adresse drizt@land.ru was unsuccessful, marked as: You message for <drizt@land.ru> from 2015/05/18 could not be delivered.
It's attached below. Reason:
---------------

4.4.0 smtp; 185.79.118.237: Socket connect timeout

**Comment by drizt** [comment]
Hi. You can use pull request to send localization me.

**Comment by pafri** [comment]
The way, I could master, would be simply: "Add attachment" :-)

**Comment by drizt** [comment]
Hm ... you can use any shared files service and just put here link. If you don't want to do PR. Anyway I will be glad to add new localization.

**Comment by pafri** [comment]
Here, the file Torrent File Editor is just ready for download: http://obvyklemisto.webgarden.cz/rubriky/soubory-ke-stazeni/preklady-rozhrani

Maybe you could use some translation server service in the future for the flexible updates, like Transifex.

**Comment by drizt** [comment]
Thanks for your advice about translation server. I never used it before. I will look it in the future.

**Comment by drizt** [comment]
I created new project on Transifex
https://www.transifex.com/projects/p/torrent-file-editor/

**Comment by drizt** [comment]
@pafri, I noticed that you made .ts file without location information. I mean in your .ts file

    <message>
        <source>Torrent File Editor</source>
        <translation>Torrent File Editor</translation>
    </message>

But must be

    <message>
        <location filename="../aboutdlg.ui" line="72"/>
        <source>Torrent File Editor</source>
        <translation>Torrent File Editor</translation>
    </message>

No *location* tag leads to wrong `lupdate` result. So it must be in translation file. Now I fix it. But please when you will update Czech translation check this tag.
