### ISSUE TITLE
if i delete some info files, i cant download the torrent anymore

### ISSUE THREAD

**Issue by bain2018** [drizt/torrent-file-editor#41]
if i delete some info files, i cant download the torrent anymore

**Comment by drizt** [comment]
When you change files in torrent torrent hash changes. So you get *new* .torrent file and can't find any peers.

**Comment by soongwoo** [comment]
Could you give me an instruction how-to-delete files in a .torrent file?
I deleted some files in 'Files' tab with '-' symbol. It does not change anything.
So, I removed some info files in 'Raw' tab. It does change .torrent file size,
but the changed .torrent file is not working.

**Comment by drizt** [comment]
If you delete files on Files tab you need to regenerate torrent (press Hammer button).

**Comment by lujunjie521** [comment]
thanks

**Comment by soongwoo** [comment]
Thx. But, I'm not the owner of the torrent.
Anyway, I appreciate your software.

Regards
soongwoo
