### ISSUE TITLE
Can't save torrent

### ISSUE THREAD

**Issue by bobbintb** [drizt/torrent-file-editor#46]
How do I save the torrent? I need to remove some files. I loaded my torrent, went to the files tab, removed the files, and saved the torrent but nothing has changed. I gave the torrent a new name so it is saving the torrent, just not any changed I made to it.

**Comment by drizt** [comment]
Use hammer button

**Comment by haodong** [comment]
save issue here

**Comment by drizt** [comment]
Here no any issue.

**Comment by snakyjake1** [comment]
I don't think the App writes out what is in the "Files" or "Tree" tab.  
It is what is in the Raw tab that it will write.
