### ISSUE TITLE
Failure after calculate piece hash

### ISSUE THREAD

**Issue by coddoge** [drizt/torrent-file-editor#48]
Version: v0.3.1 (2016/12/28)
After calculating progress dialog, always reported can't read from last file.
The last file i can open by WinRAR, and test OK.

![image](https://cloud.githubusercontent.com/assets/17444754/22918558/cbf94d4c-f2c5-11e6-93ee-9e66247df122.png)

![image](https://cloud.githubusercontent.com/assets/17444754/22918536/b9218874-f2c5-11e6-9adf-9ef9f8299c7f.png)

![image](https://cloud.githubusercontent.com/assets/17444754/22918712/982977e8-f2c6-11e6-8a35-81cfd53d6249.png)

![image](https://cloud.githubusercontent.com/assets/17444754/22918515/a8530482-f2c5-11e6-9348-92fa2f4882cc.png)

**Comment by coddoge** [comment]
But, append a blank file to end of list, the error is gone. WHY?

![image](https://cloud.githubusercontent.com/assets/17444754/22918932/fae66fca-f2c7-11e6-9fd9-e498e7d8bdd9.png)

**Comment by drizt** [comment]
Will see.

**Comment by a-roussos** [comment]
I have more or less the same problem with v0.3.9 on Windows 7 SP1 64-bit and also on Windows XP SP3 32-bit. In my case, when I click on "Calculate pieces hashes" the program can't read from the last file if the piece size is set to 1, 2, 4, 8 or 16 MiB (it will work fine if I set the piece size to any of the other values).

FWIW, I also tested it under Linux (on Fedora 27 64-bit) and it worked fine for all possible piece size values.

**Comment by drizt** [comment]
How I can reproduce this?

**Comment by a-roussos** [comment]
Thanks for the quick reply @drizt. To reproduce, please follow the steps below:
1. Download [this](https://github.com/drizt/torrent-file-editor/files/1629244/reproduce.zip) zip file (10KB) and extract it somewhere (for example the root of your C: partition)
2. Launch `torrent-file-editor-0.3.9-x64.exe`
3. Open the file `C:\reproduce.torrent`
4. Go to the _Files_ tab, and set the _Torrent root folder_ to `C:\reproduce`
5. Click on the "Calculate pieces hashes" button: you'll get the error "Can't read from C:\reproduce\256KiB"
6. Set the _Piece size_ to 2, 4, 8 or 32 MiB and click on the "Calculate pieces hashes" button: you'll get the same error. If you set the _Piece size_ to any of the other values, "Calculate pieces hashes" works fine.

**Comment by drizt** [comment]
I got it. Thanks.

**Comment by drizt** [comment]
@a-roussos 
I updated version. You can download.

**Comment by a-roussos** [comment]
Thanks for the update. I just downloaded the latest .exe and it works fine now. Nice one @drizt!
