### ISSUE TITLE
Czech localization update

### ISSUE THREAD

**Issue by pafri** [drizt/torrent-file-editor#50]
Hi, first I've updated the Transifex version - then reused .qph library to complete the latest Git version localization file. (If I remember,
[torrentfileeditor_cs.tar.gz](https://github.com/drizt/torrent-file-editor/files/925379/torrentfileeditor_cs.tar.gz)

 there is some other translation service, where I could upload it.)

**Comment by drizt** [comment]
Thanks.

**Comment by drizt** [comment]
Update packages.
