### ISSUE TITLE
TFE can't read a torrent

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#54]
TFE can't read a torrent, though I can open it via uTorrent.
[zipped torrent file.zip](https://github.com/drizt/torrent-file-editor/files/1235747/zipped.torrent.file.zip)

**Comment by drizt** [comment]
Torrent file has integer at position 2936 in strange format. Integer written as `i-4.6386732960808E+18e`. Bep3 defines integer as 

> Integers are represented by an 'i' followed by the number in base 10 followed by an 'e'.

*Number in base 10* is not defined. So I can't say is correct integer value or not?

**Comment by drizt** [comment]
File is incorrect.

**Comment by zeromido** [comment]
uTorrent can read it, though.
