### ISSUE TITLE
Line Number in Raw view

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#56]
Please number lines in Raw view (like Notepad ++)
I think it'll make syntax errors easier to check.

**Comment by drizt** [comment]
I haven't Notepad++. How exactly it should looks?

**Comment by zeromido** [comment]
[screenshot from the official website](https://notepad-plus-plus.org/assets/images/notepad4ever.gif)

**Comment by drizt** [comment]
https://i.paste.pics/e30b04db5ba75c3a2482c876b97bb831.png
