### ISSUE TITLE
Big windows executable

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#59]
@drizt Don't you think that TFE executable is quite big?

**Comment by drizt** [comment]
TFE based on cross-platform Qt. So big size is a pay for portability.

**Comment by zeromido** [comment]
So, nothing can be done about that? What about packing it with UPX for example?

**Comment by drizt** [comment]
Is it matter?

**Comment by drizt** [comment]
I try to use upx ... possible it has sense. Will think. Thanks. Please test running speed. And write here.

**Comment by zeromido** [comment]
Sure it matters. Developers who made small applications always include it in the application features' list.
Anyway, I tried UPX maximum settings (upx --ultra-brute) but it wasn't like I was expecting (9.75 MB). 
And starting TFE became slower, too. Probably packers won't be of much help.
If there is any possibility to decrease size natively without packers it would be great.

**Comment by drizt** [comment]
Only if rewrite without Qt and use only native OS API. :)

**Comment by zeromido** [comment]
OK. forget about size since it's that hard to decrease.
