### ISSUE TITLE
Mac OS X Error: This application failed to start because it could not find or load the Qt platform plugin "cocoa"

### ISSUE THREAD

**Issue by Tolsi** [drizt/torrent-file-editor#6]
I have the error on the start app 0.22 from dmg package on Mac OS X 11.10.5
```
This application failed to start because it could not find or load the Qt platform plugin "cocoa".
```
0.21 works perfectly

**Comment by Tolsi** [comment]
Sorry, I was described the problem incorrectly. I can not run the app version 0.21 and 0.22 from the Application folder, but can run 0.21 from dmg and can not run 0.22 from dmg.

**Comment by drizt** [comment]
Very helpful info. Thanks for details.

**Comment by drizt** [comment]
Maybe do you use case-sensetive file system with Application?

**Comment by Tolsi** [comment]
Yes, my fs is case-sensetive. I did it by mistake once and I could not find the time to change :)

**Comment by drizt** [comment]
Seems I fixed. Try this dmg https://fs12n1.sendspace.com/dl/525d81f516b024701d53d840ca812915/5757db9a6699749a/iwr1vo/torrent-file-editor-0.2.2.dmg

**Comment by Tolsi** [comment]
Yap, it works! Thank you!

**Comment by drizt** [comment]
Does it work in both cases from /Applications and .dmg ?

**Comment by Tolsi** [comment]
Yes

**Comment by drizt** [comment]
Thanks for bugreport.
