### ISSUE TITLE
Remember Raw tab scroll postion

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#60]
I noticed that TFE doesn't remember scroll position in _Raw_ tab.
It remembers it in _Files_ and _Tree_ tabs though.

**Comment by drizt** [comment]
It has allready implemented. But in some cases doesn't work.

**Comment by drizt** [comment]
I found real problem. When I scroll tree with mouse wheel type can changes. It's unexpected behaviour.

**Comment by zeromido** [comment]
Good job :)
Anyway, I guess the scroll position isn't remembered in _Raw_ tab because TFE reloads it every time I switch to it (the CPU usage increases momentarily when I do that).

**Comment by drizt** [comment]
Converting internal (tree) data to json is expensive operation. Unsure seems I can't optimize this.

**Comment by zeromido** [comment]
Yeah, but why doesn't TFE remember the scroll position in _Raw_ tab?
I think the reason is that TFE reloads the data every time I switch to _Raw_ tab. Is that correct? If not, why isn't it working for me?
