### ISSUE TITLE
Trojan detected from defender/MSE sourceforge/majorgeek file

### ISSUE THREAD

**Issue by cry0xen** [drizt/torrent-file-editor#62]
![tfe](https://user-images.githubusercontent.com/3743966/32301052-68fbc66e-bf86-11e7-940f-cffdbc634f97.png)

**Comment by drizt** [comment]
Probably it is false positive.

**Comment by cry0xen** [comment]
I know its a false positive and i wanted to let you know about that. another thing is why dont you release this on github? i mean compiled .exe?

**Comment by drizt** [comment]
In the past when I was doing the first release and searching a place for it I can' did this with github. So I put my .exe's on SourceForge.
