### ISSUE TITLE
Windows: do not support files larger than 2 GB

### ISSUE THREAD

**Issue by hhrhhr** [drizt/torrent-file-editor#63]
![e1](https://user-images.githubusercontent.com/966048/33802345-061a958e-dd86-11e7-99a2-d71c952dc0e1.png)
![e2](https://user-images.githubusercontent.com/966048/33802346-089e07d2-dd86-11e7-918e-8d21614feb87.png)

**Comment by drizt** [comment]
Provide your .torrent file.

**Comment by hhrhhr** [comment]
torrent file is not needed, just create a new torrent and add to it any file larger than 2 GB.

**Comment by hhrhhr** [comment]
mainwindow.cpp, @68:
````int fileSize(const QString &path)````
but Qt use quin64 as file size:
````qint64 QFileInfo::size() const````

**Comment by drizt** [comment]
It works for me.

**Comment by drizt** [comment]
![selection_113](https://user-images.githubusercontent.com/534665/33803251-34af4940-ddad-11e7-947b-dbc38f3c0c4e.png)

**Comment by hhrhhr** [comment]
It don't works for me, look at first screenshot. *torrent-file-editor-0.3.8-x32.exe* from https://sourceforge.net/projects/torrent-file-editor/
*signed int* can't be larger then 2147483647, so you either showed a torrent created in another program, or your version differs from a public one.

**Comment by drizt** [comment]
Use x64 version.

**Comment by hhrhhr** [comment]
torrent-file-editor-0.3.8-x64.exe have a same issue. But as I see, the source is already fixed an hour ago. I hope that the binaries will also be updated.

**Comment by drizt** [comment]
I downloaded .torrent from Rutracker and test it with both torrent-file-editor-0.3.8-x32.exe and torrent-file-editor-0.3.8-x64.exe. Files tab shows correct size. It strange for me that it doesn't work for you. Probably correct question should be why I don't get such bug?

**Comment by hhrhhr** [comment]
I am **not downloaded** .torrent but **create new**, as descrition say "... tool designed to **create** and edit".

**Comment by drizt** [comment]
Telepaths on vocation. Without steps to reproduce I can't know how you got this. Just small advice for future.

I plan to release tomorrow.

**Comment by hhrhhr** [comment]
You do not need to be a telepath to read the third post and understand that it was about **creating**, not editing.
