### ISSUE TITLE
How to define folder structure?

### ISSUE THREAD

**Issue by snakyjake1** [drizt/torrent-file-editor#64]
How can I define the folder structure (directories and sub-directories)?

**Comment by snakyjake1** [comment]
I found a feature buried in the Tree tab.
Is there an easier way to set the global file path?

**Comment by drizt** [comment]
See #69

**Comment by snakyjake1** [comment]
Great product....
Here are some observations, and more clarity on the relative path issue...

(1) This should be the relative folder path, part of the torrent metadata.
(2) Want sort order that correctly sorts by numbers.
(3) This should show root/parent folder path, and won't be part of the torrent metadata.
(1) + (3) = The complete path to the torrent.

![Image 1](https://i.imgur.com/csyBsd0.png)

Here is what the sort order should look like:
![Image 2](https://i.imgur.com/5o13cUu.png)

Relative paths not in the Tree tab:
![Image 3](https://i.imgur.com/645WAmq.png)

I first added the information to the Main tab, but after calculating the pieces, the "Name" field was reset.  I want the torrent to be named differently than the folder:
![Image 4](https://i.imgur.com/yXN6h7e.png)

If you want relative path, you can add the path with the Raw tab.
This is tedious for a lot of files, and easy to make a mistake.
![Image 5](https://i.imgur.com/AXw20Xy.png)

The next trick is to recalculate the has pieces after modifying the path.
I successfully created one torrent doing relative paths, just can't remember the steps.
The easiest thing would be for the App to recalacule the pieces hash, after I added the relative path.  The App will need to concatenate the Root text box (10) and the Path column (11).
![Image 5](https://i.imgur.com/nRtcZGh.png)

**Comment by snakyjake1** [comment]
I finally got the problem with the "Torrent root folder is not set" "fixed".  I removed the the relative path from the "Torrent root folder" text box.  It changed the "Path" column.  It correctly didn't mess-up the path in the Raw tab.

But now I get strange issues recalculating the pieces:
1)  If I reload from Raw, I get duplicates in the Files tab.
2)  The App creates a blank Pieces attribute in the Tree tab.
3)  It doesn't correctly calculate the pieces hash either.  I'm not sure what the App is using for inputs to calculate the hash.

...to be continued...

**Comment by snakyjake1** [comment]
Another success !
I started from scratch...

This time I (if I remember what I did correctly):
1)  Add info to Main tab.
2)  Add files to Files tab.
3)  Calculate.
4)  Update Raw with path information (this is extremely tedious).
5)  Since Calculating in (3) re-updates the torrent name, I have to redo the name.
6)  Save.
7)  Test.

![Image 4](https://i.imgur.com/JdUZK3W.png)

**Comment by drizt** [comment]
Probably you don't understand how to work .torrent files. When .torrent file contains *many* files result file path will be *$download_path/$torrent_name/$relative_path_in_info*.

For example I opened *Babylon 5.torrent* file in qbittorrent and downloaded the first file. So *Babylon5_S5E01_No.Compromises.mkv* is located in */home/taurus/Downloads/Babylon5.Season5*. Look at screenshots.

![babylon5 season5_138](https://user-images.githubusercontent.com/534665/34465698-d65489fc-eeda-11e7-868c-dd8229f67adc.png)
![babylon-5 torrent - torrent file editor_139](https://user-images.githubusercontent.com/534665/34465699-ecaf777a-eeda-11e7-9c3a-4271a07542ce.png)
![babylon-5 torrent - torrent file editor_140](https://user-images.githubusercontent.com/534665/34465700-f26ebd06-eeda-11e7-9b46-33d465995643.png)
![babylon-5 torrent - torrent file editor_141](https://user-images.githubusercontent.com/534665/34465701-f7274c46-eeda-11e7-9650-3ee2e62fcbce.png)
![babylon5 season5 dolphin_142](https://user-images.githubusercontent.com/534665/34465702-fbc6c592-eeda-11e7-982b-6b056fbbd5f1.png)

**Comment by drizt** [comment]
> 1. If I reload from Raw, I get duplicates in the Files tab.
> 2. The App creates a blank Pieces attribute in the Tree tab.

Fixed at 320dc2fdab8862530f4658669ca3856f7e48ce7a. Thanks.
