### ISSUE TITLE
Torrent root folder is not set....but it is!

### ISSUE THREAD

**Issue by snakyjake1** [drizt/torrent-file-editor#67]
When I click the button "Calculate Pieces Hash", I keep getting a dialog the root folder is not set.
Both the "Torrent root folder" and the "Path" appear to be correct.

![2017-12-30 15_59_24](https://user-images.githubusercontent.com/8312560/34458135-85884f64-ed7b-11e7-80f9-7bfe70c03251.png)

**Comment by snakyjake1** [comment]
It looks like the "Torrent root folder" isn't actually being used, and the App is looking at the file "Path" column instead.

The reason why the Path column is different is because I want a relative path for the torrent folder structure.

**Comment by snakyjake1** [comment]
I need:
Path = relative path+file

If I click the Hammer icon to recalculate the Info Hash, I need:
"Torrent Root Folder" + "Path"

**Comment by drizt** [comment]
If you see relative path in *Path* column it means that app can't found the file. In .torrent full pathese are not used. So in .torrent file you always get relative path.

**Comment by drizt** [comment]
Fixed at 92361c5542a0bb955379af2380a3e74365a23d35.
