### ISSUE TITLE
How do you re-order files, and recalculate?

### ISSUE THREAD

**Issue by snakyjake1** [drizt/torrent-file-editor#68]
I re-ordered the torrent files, but now the hash doesn't validate.
How do I re-calculate the hash?

**Comment by drizt** [comment]
You need to set correct *Torrent root folder* before and check that files have full path. Full path means that file is found on the disk.

**Comment by drizt** [comment]
Fixed at 92361c5542a0bb955379af2380a3e74365a23d35.
