### ISSUE TITLE
Requesting relative path folders

### ISSUE THREAD

**Issue by snakyjake1** [drizt/torrent-file-editor#69]
I need my files organized in subfolders.
There's an App conflict between what I can edit in the Raw tab and the Files tab and the hashes.

**Comment by drizt** [comment]
You need to use your system file manager for this purposes. It's not a task for *Torrent File Editor*.

**Comment by snakyjake1** [comment]
The system file structure is setup.  

Why can't Torrent File Editor write the folder/subfolder structures to Raw?

**Comment by drizt** [comment]
*Torrent File Editor* does it. Show your problem.
