### ISSUE TITLE
Improve Japanese translation

### ISSUE THREAD

**Issue by b25rb2hkb25kbw** [drizt/torrent-file-editor#70]
Hi, I found this app on Google and thought that this is a great one.
But I had an issue: the Japanese translation was so awful.  Maybe this is because it was translated by Google translation or something.
Fortunately, I could help you by providing proper translations, but I'm quite new to Qt, so I'm not sure what file I have to edit. 

I guess all I have to do is to modify https://github.com/drizt/torrent-file-editor/blob/master/translations/torrentfileeditor_ja.ts , is that right? 
Do I have to use some specific Qt editor or can I just edit it using normal text editor?
Are there any points I have to care about?

Also, I wish there is some way to change language of the app.  (Had I better create a new issue for that?)
Thank you.

**Comment by drizt** [comment]
Hi. Thanks you. I didn't check Japanese translation or any other. Really I can't do this. Someone translated TFE to Japanese and give me a result.

About how to do translation. Sure you can to direct editing of **torrentfileeditor_ja.ts**. But it's not a best way to do this. For translations is preferable way to use [Crowdin](https://crowdin.com/project/torrent-file-editor/ja#) translation service. Or you can use Qt Linguist to locally edit .ts files. To get Qt Linguist need to install whole Qt IDE.

About app language. App language relates from system language. So you need to change system language (or do such that app will think that another system language is set). The particular way how to do it relates from you OS. And sure you can open new issue with change language feature request.

**Comment by b25rb2hkb25kbw** [comment]
I added some translations and also upvoted the others.  Now almost all the translation is OK.  I added some comments there, some of which are questions.

**Comment by drizt** [comment]
Fixed here https://github.com/drizt/torrent-file-editor/commit/414b95a36419c372f4927b6c4371e44cd8ddd5bc
