### ISSUE TITLE
may i ask cmd parameter support

### ISSUE THREAD

**Issue by navmesh** [drizt/torrent-file-editor#72]
hello, thank you very much for awesome program, it helps me so much
may i ask for a feature : 
cmd parameter to run 
for example, if i want to get file list, file size , and hash to text or clipboard .
i would run the command torrent-file-editor.exe -getfilelist to get list of file names to clipboard
similarly torrent-file-editor.exe -getfilesize to get list of file size to clipboard

or an menu to copy the value of selected column to clipboard in UI MENU
Thank you very much

**Comment by drizt** [comment]
Just now you can copy the selected file list from **Files** tab with **Ctrl+C**. Only names without sizes.

**Comment by navmesh** [comment]
I see, thank you for the help , i hope to see it available in the future 
it would be much helpful for the user to automate the process

**Comment by drizt** [comment]
![selection_055](https://user-images.githubusercontent.com/534665/42721987-5402f404-875d-11e8-9c72-cdd2f744857f.png)
Is it OK for your needs? I use **tab** to split file name from file size.

**Comment by navmesh** [comment]
omg that's so fast
Thank you very much, i really appreciate it 
if possible ,i think it would be much helpful if we have a hotkey for "copy with size" menu,for example ctrl + shift + c or something,like you did ctrl + c with "copy"
but it's already awesome anyway,thank you :)

**Comment by drizt** [comment]
Fixed here https://github.com/drizt/torrent-file-editor/commit/414b95a36419c372f4927b6c4371e44cd8ddd5bc. I built new version with these changes you can download it from SourceForge.

**Comment by navmesh** [comment]
That's great !
thank you very much , i really appreciate it :)
