### ISSUE TITLE
Syntax error, unexpected invalid

### ISSUE THREAD

**Issue by YellowSM** [drizt/torrent-file-editor#75]
"Source" tab. Error on  parameter "creation date"
This occurs on all torrent-files.

![te-syntax-error](https://user-images.githubusercontent.com/5058386/43048927-628d5b4e-8df8-11e8-8c3b-f71cc7dbe3ff.jpg)

**Comment by drizt** [comment]
Works for me. Please provide your .torrent file.

**Comment by YellowSM** [comment]
For example: 
[Lukyanenko_S_-_Malchik_i_t'ma.zip](https://github.com/drizt/torrent-file-editor/files/2229606/Lukyanenko_S_-_Malchik_i_t.ma.zip)

I'm tried windows version 0.3.11 (x86 and x64)

**Comment by drizt** [comment]
I have no error. What your system?

**Comment by YellowSM** [comment]
My system is Win 7 x64
I run the program and drag the torrent into the program window. Then I open the tab and see the that error.
Or I run program with filename as parameter. And i get the same error

Well, this does not affect the operability of the program. So it does not really matter...

**Comment by YellowSM** [comment]
I understood. The problem is in quotes. If I add quotes to the value of the parameter "creation date", I get the following error on the parameter without quotes.
![sye-1](https://user-images.githubusercontent.com/5058386/43267029-891b51c6-90f5-11e8-9fd1-4b016b3ff373.png)

![sye-2](https://user-images.githubusercontent.com/5058386/43267042-93420550-90f5-11e8-9630-258d4dd1e565.png)

**Comment by drizt** [comment]
Very strange. I have Win 7 x64 too.

**Comment by drizt** [comment]
Seems it's a QJSON bug flavio/qjson#48

**Comment by drizt** [comment]
Try this version https://sourceforge.net/projects/torrent-file-editor/files/test/

**Comment by drizt** [comment]
I reproduced on Windows. Need to input very big number and when error will be showed remove the number. Error will be on screen. So seems 'strtoull' not reset errno value.

**Comment by YellowSM** [comment]
> Try this version

Yeah, now no errors. I think that's enough.  It's unlikely that the .torrents will have too large numbers.

**Comment by drizt** [comment]
I uploaded 0.3.12 version with applied fix for this issue. You can download from SourceForge.
