### ISSUE TITLE
[REQ] Out JSON to stdout in commandline

### ISSUE THREAD

**Issue by Baltazar500** [drizt/torrent-file-editor#80]
Need out JSON to stdout in commandline

**Comment by drizt** [comment]
On UNIX you can do `torrent-file-editor --to-json your.json /dev/stdout`. On Windows this feature seems useless due specific commandline. GUI-application can't use *owner* commandline, only possible to open a new command line and use it. You probably note that when you call `torrent-file-editor --help` from command line it opens another commandline window to show help.

**Comment by drizt** [comment]
Also I tried `torrent-file-editor.exe --to-json my.torrent CON`. It say: *Error: can't open destination file*
