### ISSUE TITLE
Is it possible to install in Raspberry Pi?

### ISSUE THREAD

**Issue by kdantas** [drizt/torrent-file-editor#82]
Hi, is it possible to install Torrent File Editor (GUI Mode) on Raspberry Pi 3 with Raspbian Stretch OS? If possible, someone can give me the step by step, because I'm new to Linux and its command lines.Thanks.

**Comment by drizt** [comment]
You need to have Qt5 on your Raspbian Stretch OS. Then you can compile TFE for yourself. Qt have some instructions [1](https://wiki.qt.io/Raspberry_Pi_Beginners_Guide), [2](https://doc.qt.io/QtForDeviceCreation/qtee-preparing-hardware-rasberrypi.html) and [3](https://wiki.qt.io/Native_Build_of_Qt5_on_a_Raspberry_Pi). Unsure I never seen Raspberry and can't help you. Anyway you need to have development version Qt5 (Qt5 with headers files and .so files and other for building files) to compile TFE.
