### ISSUE TITLE
Drive letter is added to path attribute when adding multiple files from a drive root

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#83]
Steps to Reproduce:
Start TFE, switch to _Files_ tab, click _Add files_, choose multiple files (minimum two files) from a drive's root (for example, D:\test1.txt and D:\test2.txt), click Open, click _Calculate pieces hashes_ and wait for it to finish, switch to _Raw_ tab, you'll see that the drive letter is added to the path:
    "path" : [
     "D:",
     "test1.txt"
However, if the files added are anywhere else other than the root, the drive letter will not be added to the path.

**Comment by drizt** [comment]
You shouldn't put file*s* from drive's root. All files must be located in one common folder. In your case test1.txt and test2.txt haven't commont root. But you right TFE doesnt handle this case. In such case app must explicity warn user.
