### ISSUE TITLE
One-file torrents cannot be renamed without changing the file's name

### ISSUE THREAD

**Issue by zeromido** [drizt/torrent-file-editor#86]
Because a one-file torrent doesn't have the _path_ property and only relies on the _name_ property, if a user wants to modify a one-file torrent name the file's name would also be changed.

Example of a torrent lacking the _files_ property:
``` json
{
 "creation date" : 1554846637,
 "encoding" : "UTF-8",
 "info" : {
  "length" : 4,
  "name" : "New Text Document.txt",
  "piece length" : 16384,
  "pieces" : "%98H%16%fd2%96\"%87n%14%90v4&No3.%9f%b3"
 }
}
```

The "fixed" torrent file
``` json
{
 "creation date" : 1554846637,
 "encoding" : "UTF-8",
 "info" : {
  "files" : [
   {
    "length" : 4,
    "path" : [
     "New Text Document.txt"
    ]
   }
  ],
  "name" : "New Text Document.txt",
  "piece length" : 16384,
  "pieces" : "%98H%16%fd2%96\"%87n%14%90v4&No3.%9f%b3"
 }
}
```

Note:
This behavior is shared by TFE and uTorrent

**Comment by drizt** [comment]
I corrected your Markdown. There is more good way to show code pieces.

**Comment by drizt** [comment]
Probably it's a format limitations. Need to read torrent documentation. Hm can you open "fixed" .torrent file in uTorrent?

**Comment by drizt** [comment]
Hm in case of "fixed" .torrent file actual file wille be downloaded to /some/path/New Text Document.txt/New Text Document.txt. Yes in this case you free to change name but you get extra folder. Do you sure that this exactly what you want?

**Comment by zeromido** [comment]
> Probably it's a format limitations

You're right:
http://www.bittorrent.org/beps/bep_0003.html
> In the single file case, **the name key is the name of a file**, in the multiple file case, it's the name of a directory.

See also:
https://wiki.theory.org/index.php/BitTorrentSpecification#Info_in_Single_File_Mode
> can you open "fixed" .torrent file in uTorrent?

Yes.
> actual file will be downloaded to /some/path/New Text Document.txt/New Text Document.txt

No, there won't be any extra folders. You can see it yourself in _Files_ tab and/or uTorrent.

Anyway, since it's a format limitation I will have to ignore this and close the issue.
